-- Script generated by Redgate Compare v1.62.5.5054



-- deployment: Creating default.employees...
CREATE TABLE `default`.`employees` (
    `employee_id` bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    `first_name` string NOT NULL,
    `last_name` string NOT NULL,
    `title` string,
    `region_id` bigint,
    CONSTRAINT `employees_pk` PRIMARY KEY (`employee_id`)
);


-- deployment: Creating default.suppliers...
CREATE TABLE `default`.`suppliers` (
    `supplier_id` bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    `supplier_name` string NOT NULL,
    `contact_name` string,
    `address` string,
    `region_id` bigint,
    CONSTRAINT `suppliers_pk` PRIMARY KEY (`supplier_id`)
);


-- deployment: Creating default.regions...
CREATE TABLE `default`.`regions` (
    `region_id` bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    `region_name` string NOT NULL,
    CONSTRAINT `regions_pk` PRIMARY KEY (`region_id`)
);


-- deployment: Creating default.employees.employees_regions_fk...
ALTER TABLE `default`.`employees` ADD CONSTRAINT `employees_regions_fk` FOREIGN KEY (`region_id`) REFERENCES `default`.`regions` (`region_id`);


-- deployment: Creating default.suppliers.suppliers_regions_fk...
ALTER TABLE `default`.`suppliers` ADD CONSTRAINT `suppliers_regions_fk` FOREIGN KEY (`region_id`) REFERENCES `default`.`regions` (`region_id`);


-- deployment: Creating default.categories...
CREATE TABLE `default`.`categories` (
    `category_id` bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    `category_name` string NOT NULL,
    `description` string,
    CONSTRAINT `categories_pk` PRIMARY KEY (`category_id`)
);


-- deployment: Creating default.products...
CREATE TABLE `default`.`products` (
    `product_id` bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) COMMENT 'Unique identifier assigned to each product in the inventory, used to reference and manage products.',
    `product_name` string NOT NULL COMMENT 'Name of the product as it appears for sale or in the catalog, useful for identification and display purposes.',
    `supplier_id` bigint COMMENT 'Identifier linking the product to its supplier, allowing tracking of product sources and managing supplier relationships.',
    `category_id` bigint COMMENT 'Identifier that associates the product with a specific category, helping to organize products into groups for easier navigation and analysis.',
    `quantity_per_unit` string COMMENT 'Description of the amount or packaging size of the product, indicating how the product is quantified or sold (e.g., ''24 - 12 oz bottles'').',
    `unit_price` decimal(10,2) COMMENT 'The selling price per unit of the product, essential for pricing, billing, and sales calculations.',
    `units_in_stock` int COMMENT 'Current quantity of the product available in inventory, used to monitor stock levels and manage replenishment needs.',
    CONSTRAINT `products_pk` PRIMARY KEY (`product_id`)
);


-- deployment: Creating default.products.products_suppliers_fk...
ALTER TABLE `default`.`products` ADD CONSTRAINT `products_suppliers_fk` FOREIGN KEY (`supplier_id`) REFERENCES `default`.`suppliers` (`supplier_id`);


-- deployment: Creating default.products.products_categories_fk...
ALTER TABLE `default`.`products` ADD CONSTRAINT `products_categories_fk` FOREIGN KEY (`category_id`) REFERENCES `default`.`categories` (`category_id`);


-- deployment: Creating default.shippers...
CREATE TABLE `default`.`shippers` (
    `shipper_id` bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    `shipper_name` string NOT NULL,
    `phone` string,
    CONSTRAINT `shippers_pk` PRIMARY KEY (`shipper_id`)
);



-- deployment: Creating default.customers...
CREATE TABLE `default`.`customers` (
    `customer_id` bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    `customer_name` string NOT NULL,
    `contact_name` string,
    `address` string,
    `region_id` bigint,
    CONSTRAINT `customers_pk` PRIMARY KEY (`customer_id`)
);


-- deployment: Creating default.customers.customers_regions_fk...
ALTER TABLE `default`.`customers` ADD CONSTRAINT `customers_regions_fk` FOREIGN KEY (`region_id`) REFERENCES `default`.`regions` (`region_id`);

