-- Script generated by Redgate Compare v1.62.6.5135


-- deployment: Dropping default.recent_orders...
DROP VIEW `default`.`recent_orders`;


-- deployment: Dropping default.orders.orders_shippers_fk...
ALTER TABLE `default`.`orders` DROP CONSTRAINT `orders_shippers_fk`;


-- deployment: Dropping default.orders.orders_employees_fk...
ALTER TABLE `default`.`orders` DROP CONSTRAINT `orders_employees_fk`;


-- deployment: Dropping default.orders.orders_customers_fk...
ALTER TABLE `default`.`orders` DROP CONSTRAINT `orders_customers_fk`;


-- deployment: Dropping default.orders...
DROP TABLE `default`.`orders`;

