-- Script generated by Redgate Compare v1.62.7.5446


-- deployment: Dropping default.products.products_categories_fk...
ALTER TABLE `default`.`products` DROP CONSTRAINT `products_categories_fk`;


-- deployment: Creating default.RG_Recovery_1_categories...
CREATE TABLE `default`.`RG_Recovery_1_categories` (
    `category_id` bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    `category_name` string NOT NULL,
    `description` string
);
INSERT INTO `default`.`RG_Recovery_1_categories` (`category_name`, `description`)
SELECT `category_name`, `description`
FROM `default`.`categories`;


-- deployment: Dropping default.categories...
DROP TABLE `default`.`categories`;


-- deployment: Renaming default.RG_Recovery_1_categories...
ALTER TABLE `default`.`RG_Recovery_1_categories` RENAME TO `default`.`categories`;


-- deployment: Creating default.categories.categories_pk...
ALTER TABLE `default`.`categories` ADD CONSTRAINT `categories_pk` PRIMARY KEY (`category_id`);


-- deployment: Creating default.products.products_categories_fk...
ALTER TABLE `default`.`products` ADD CONSTRAINT `products_categories_fk` FOREIGN KEY (`category_id`) REFERENCES `default`.`categories` (`category_id`);

