-- Script generated by Redgate Compare v1.63.0.5640


-- deployment: Dropping default.products.products_categories_fk...
ALTER TABLE `default`.`products` DROP CONSTRAINT `products_categories_fk`;


-- deployment: Creating default.RG_Recovery_1_categories...
CREATE TABLE `default`.`RG_Recovery_1_categories` (
    `category_id` bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    `category_name` string NOT NULL,
    `description` string,
    `category_type` string
);
INSERT INTO `default`.`RG_Recovery_1_categories` (`category_name`, `description`, `category_type`)
SELECT `category_name`, `description`, `category_type`
FROM `default`.`categories`;


-- deployment: Dropping default.categories...
DROP TABLE `default`.`categories`;


-- deployment: Renaming default.RG_Recovery_1_categories...
ALTER TABLE `default`.`RG_Recovery_1_categories` RENAME TO `default`.`categories`;


-- deployment: Creating default.categories.categories_pk...
ALTER TABLE `default`.`categories` ADD CONSTRAINT `categories_pk` PRIMARY KEY (`category_id`);


-- deployment: Creating default.products.products_categories_fk...
ALTER TABLE `default`.`products` ADD CONSTRAINT `products_categories_fk` FOREIGN KEY (`category_id`) REFERENCES `default`.`categories` (`category_id`);


-- deployment: Altering default.recent_orders...
ALTER VIEW `default`.`recent_orders` AS SELECT o.order_id, o.order_date, c.customer_name, e.first_name, e.last_name, s.shipper_name
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN employees e ON o.employee_id = e.employee_id
JOIN shippers s ON o.shipper_id = s.shipper_id
WHERE o.order_date >= DATEADD(day, -7, CURRENT_DATE);

