-- Script generated by Redgate Compare v1.62.6.5135


-- deployment: Creating default.orders...
CREATE TABLE `default`.`orders` (
    `order_id` bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    `customer_id` bigint,
    `employee_id` bigint,
    `shipper_id` bigint,
    `order_date` date,
    `required_date` date,
    `shipped_date` date,
    CONSTRAINT `orders_pk` PRIMARY KEY (`order_id`)
);


-- deployment: Creating default.recent_orders...
CREATE VIEW `default`.`recent_orders` AS SELECT o.order_id, o.order_date, c.customer_name, e.first_name, e.last_name, s.shipper_name
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN employees e ON o.employee_id = e.employee_id
JOIN shippers s ON o.shipper_id = s.shipper_id
WHERE o.order_date >= DATEADD(day, -7, CURRENT_DATE);


-- deployment: Creating default.orders.orders_shippers_fk...
ALTER TABLE `default`.`orders` ADD CONSTRAINT `orders_shippers_fk` FOREIGN KEY (`shipper_id`) REFERENCES `default`.`shippers` (`shipper_id`);


-- deployment: Creating default.orders.orders_employees_fk...
ALTER TABLE `default`.`orders` ADD CONSTRAINT `orders_employees_fk` FOREIGN KEY (`employee_id`) REFERENCES `default`.`employees` (`employee_id`);


-- deployment: Creating default.orders.orders_customers_fk...
ALTER TABLE `default`.`orders` ADD CONSTRAINT `orders_customers_fk` FOREIGN KEY (`customer_id`) REFERENCES `default`.`customers` (`customer_id`);

