-- Script generated by Redgate Compare v1.63.0.5640


-- deployment: Altering default.recent_orders...
ALTER VIEW `default`.`recent_orders` AS SELECT o.order_id, o.order_date, c.customer_name, e.first_name, e.last_name, s.shipper_name
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN employees e ON o.employee_id = e.employee_id
JOIN shippers s ON o.shipper_id = s.shipper_id
WHERE o.order_date >= DATEADD(day, -7, CURRENT_DATE);


-- deployment: Creating default.categories.foo...
ALTER TABLE `default`.`categories` ADD COLUMN (`foo` string);


-- deployment: Creating default.categories.category_type_description...
ALTER TABLE `default`.`categories` ADD COLUMN (`category_type_description` string);

